import 'bootstrap/dist/css/bootstrap.min.css'; // Global Bootstrap styles
import localFont from "next/font/local";
import './globals.css'; // Your custom global styles
import NavBar from './components/NavBar/NavBar';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Render the NavBar on top of each page */}
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
